name: Bug Report
description: How many legs does the bug have? Are you from Australia? Answer more questions in this form
title: "[BUG]: "
labels: ["bug"]
assignees:
  - kiluho
body:
- type: textarea
  attributes:
    label: Please describe this bug
    description: "Please provide a detailed description of the issue. If necessary, upload screenshots using the button below."
    placeholder: "Example: When I start my game it crashes and tells me to follow kiluho on Twitch. I attached a picture of my feet. ..."
  validations:
    required: true
- type: input
  attributes:
    label: "Which version of kiluho's Keystrokes are you using?"
    placeholder: "Example: 1.0.5"
  validations:
    required: true
- type: dropdown
  attributes:
    label: Which operating system are you using?
    description: Please prodide addtional details, like version numbers, below.
    options:
      - label: macOS
      - label: Windows
      - label: Linux
  validations:
    required: true
- type: input
  attributes:
    label: Which Minecraft version are you using?
    placeholder: "Example: 1.21.10"
  validations:
    required: true
- type: textarea
  attributes:
    label: Are there any additional details?
    description: "If necessary, provide any additional details for this bug."
    placeholder: "Example: I accidentally slipped on a banana this morning, maybe that caused this?"
